apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: 1.30.3
clusterName: rmccu-k8s-cluster
controlPlaneEndpoint: "load-balancer.homelab.lan:7443"
networking:
  podSubnet: "172.18.0.0/16"
  serviceSubnet: "10.244.0.0/16"
apiServer:
  certSANs:
    - load-balancer.homelab.lan
    - 192.168.20.5
  timeoutForControlPlane: "5m0s"
