apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik-v3
  annotations:
    metallb.universe.tf/address-pool: loadbalancer-vip
    metallb.universe.tf/allow-shared-ip: "true"
  labels:
    app: traefik
spec:
  type: NodePort
  selector:
    app: traefik
  ports:
    - name: web
      port: 80
      nodePort: 30080
      targetPort: 80
    - name: websecure
      port: 443
      nodePort: 30443
      targetPort: 444