# Taken care of with the cert-manager_v1.13.1.crds.yaml file
# downloaded from www.github.com/cert-manager/cert-manager
installCRDs: false
replicaCount: 3
extraArgs:
  - --dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53
  - --dns01-recursive-nameservers-only
podDnsPolicy: None
podDnsConfig:
  nameservers:
    - "1.1.1.1"
    - "8.8.8.8"