apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-certs-volume
spec:
  storageClassName: traefik-certs
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
    Retain
  nfs:
    server: pve-nfs-server
    path: /k8s-cluster/charts/traefik/ssl-certs
    readOnly: false
