apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rchomelab-com
  namespace: origin-ca-issuer
spec:
  secretName: rchomelab-com-tls
  dnsNames:
    - rchomelab.com
    - "*.rchomelab.com"
  duration: 168h
  renewBefore: 24h
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: OriginIssuer
    name: cloudflare-origin-ca-issuer