apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
ports:
  - name: web-traffic
    protocol: TCP
    port: 8080
    targetPort: web
    nodePort: 30080
  - name: websecure-traffic
    protocol: TCP
    port: 8443
    targetPort: websecure
    nodePort: 30443
  - name: metrics-traffic
    protocol: TCP
    port: 9100
    targetPort: metrics
    nodePort: 30901
  - name: traefik-dashboard
    protocol: TCP
    port: 9001
    targetPort: traefik
    nodePort: 30091
externalIPs:
  - 192.168.3.10
spec:
  type: LoadBalancer
  selector:
    app: traefik
    namespace: traefik
#  loadBalancerSourceRanges: []
status:
  loadBalancer:
    ingress:
    - ip: 192.168.3.10