---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: traefik-dash-auth
  namespace: traefik
data:
  username: <base64_encoded_username>
  password: <base64_encoded_password>
