apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
  name: cloudflare-origin-ca-issuer
  namespace: origin-ca-issuer
spec:
  requestType: OriginECC
  auth:
    serviceKeyRef:
      name: origin-issuer-secret
      key: key