---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rc-server
  namespace: traefik
spec:
  secretName: rc-server-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - "*.rc-server.com"
  - "rc-server.com"