---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rchomelab
  namespace: traefik
spec:
  secretName: rchomelab-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - "*.rchomelab.com"
  - "rchomelab.com"