---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <cloudflare_email> # replace with cloudflare email
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: <notifier_email> # replace with email for notifications
            apiTokenSecretRef:
              name: cert-manager-cf-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "rchomelab.com"
