apiversion: v1
Kind: Secret
metadata:
  name: cf-creds
  namespace: traefik
type: Opaque
stringData:
 ########################################################################################################
 #    NOTE TO SELF: DON'T FORGET TO ADD CLOUDFLARE EMAIL AND GLOBAL API KEY HERE AND ENCRYPT FILE!!!    #
 ########################################################################################################
   email:  <cf_email>
   apiToken: <cf_api_key>
