apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
spec:
  type: LoadBalancer
  selector:
    app: traefik
    namespace: traefik
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: websecure
      protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: 30443
    - name: metrics
      protocol: TCP
      port: 9100
      targetPort: 9100
      nodePort: 30901
    - name: traefik
      protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30091
  externalIPs:
    - 192.168.3.10
  loadBalancerSourceRanges: []