apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  type: LoadBalancer
  selector:
    app: traefik
  externalIPs:
    - 192.168.3.10
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: traefik
    - name: https
      protocol: TCP
      port: 8443
      targetPort: traefik
    - name: admin
      protocol: TCP
      port: 9001
      targetPort: traefik
