apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: vip-peer
spec:
  peerIP: 192.168.20.5
  asNumber: 65202
  filters:
  - deny-internal-service-network
  - deny-pod-network
  - import-external-routes
  - export-external-service-network
---
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: pfsense-peer
spec:
  peerIP: 10.10.10.1
  asNumber: 65200
  filters:
  - deny-internal-service-network
  - deny-pod-network
  - import-external-routes
  - export-external-service-network