
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: vip-peer
spec:
  peerIP: 192.168.20.5
  asNumber: 65202
  filters:
  -  import-external-routes
  -  export-external-service-network
  -  deny-internal-service-network
  -  deny-pod-network