
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: router
spec:
  peerIP: 10.10.10.1
  asNumber: 65200
  filters:
  -  import-external-routes
  -  export-external-service-network
  -  deny-internal-service-network
  -  deny-pod-network