apiVersion: apps/v1
kind: Deployment

metadata:
  name: traefik-deployment
  namespace: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik

  persistence:
    enabled: true
    name: ssl-certs
    existingClaim: "traefik-certs-claim"
    path: /ssl-certs
    annotations: {}

  initContainers:
  # The "volume-permissions" init container is required if you run into permission issues.
  # Related issue: https://github.com/traefik/traefik-helm-chart/issues/396
   - name: volume-permissions
     image: busybox:latest
     command: ["sh","-c","chmod -vR 600 /ssl-certs/*"]
     securityContext:
       runAsNonRoot: true
       runAsGroup: 65532
       runAsUser: 65532
     volumeMounts:
       - name: ssl-certs
         mountPath: /ssl-certs

  resources:
    requests:
      cpu: "500m"
      memory: "300Mi"
    limits:
      cpu: "1000m"
      memory: "600Mi"

    spec:
      serviceAccountName: traefik-service-account
      containers:
        - name: traefik
          image: traefik:v2.10
          args:
            - --api.insecure
            - --providers.kubernetesingress
          ports:
            - name: web
              containerPort: 8080
              exposedPort: 8080
              targetPort: 8080
              nodePort: 30080
            - name: websecure
              containerPort: 8443
              exposedPort: 8443
              targetPort: 8443
              nodePort: 30443
            - name: metrics
              containerPort: 9100
              exposedPort: 9100
              targetPort: 9100
              nodePort: 30901
            - name: dashboard
              containerPort: 9001
              exposedPort: 9001
              targetPort: 9001
              nodePort: 30091





    metrics:
      prometheus:
        entryPoint: metrics