apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  type: LoadBalancer
  selector:
    app: traefik
  externalIPs:
    - 192.168.3.10
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 35001
    - name: https
      protocol: TCP
      port: 443
      targetPort: 35002
    - name: admin
      protocol: TCP
      port: 9000
      targetPort: 35003
