global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        # See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.>
        ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128>
        ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SH>
        ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend kubernetes-frontend
        bind *:6443
        mode tcp
        option tcplog
        default_backend kube-apiserver

backend kube-apiserver
        option httpchk GET /healthz
        http-check expect status 200
        mode tcp
        option ssl-hello-chk
        balance roundrobin
        server k8s-master-01 192.168.3.11:6443 check fall 3 rise 2
        server k8s-master-02 192.168.3.12:6443 check fall 3 rise 2
        server k8s-master-03 192.168.3.13:6443 check fall 3 rise 2

frontend traefik-frontend-no-tls
        bind *:8080
        mode tcp
        option tcplog
        default_backend traefik-backend-no-tls


frontend traefik-frontend-tls
        bind *:8443
        mode tcp
        option tcplog
        default_backend traefik-backend-tls

frontend traefik-frontend-dash
        bind *:9001
        mode tcp
        option tcplog
        default_backend traefik-backend-dash

backend traefik-backend-no-tls
        option httpchk GET /healthz
        http-check expect status 200
        mode tcp
        option ssl-hello-chk
        server worker-node-01 192.168.3.14:8080 check fall 3 rise 2
        server worker-node-02 192.168.3.15:8080 check fall 3 rise 2
        server worker-node-03 192.168.3.16:8080 check fall 3 rise 2
        server worker-node-04 192.168.3.17:8080 check fall 3 rise 2
        server worker-node-05 192.168.3.18:8080 check fall 3 rise 2

backend traefik-backend-tls
        option httpchk GET /healthz
        http-check expect status 200
        mode tcp
        option ssl-hello-chk
        server worker-node-01 192.168.3.14:8443 check fall 3 rise 2
        server worker-node-02 192.168.3.15:8443 check fall 3 rise 2
        server worker-node-03 192.168.3.16:8443 check fall 3 rise 2
        server worker-node-04 192.168.3.17:8443 check fall 3 rise 2
        server worker-node-05 192.168.3.18:8443 check fall 3 rise 2


backend traefik-backend-dash
        option httpchk GET /healthz
        http-check expect status 200
        mode tcp
        option ssl-hello-chk
        server worker-node-01 192.168.3.14:9001 check fall 3 rise 2
        server worker-node-02 192.168.3.15:9001 check fall 3 rise 2
        server worker-node-03 192.168.3.16:9001 check fall 3 rise 2
        server worker-node-04 192.168.3.17:9001 check fall 3 rise 2
        server worker-node-05 192.168.3.18:9001 check fall 3 rise 2
